import { EMySkillRelation, type MSkill } from './models/skill.model.js';

export const skillsData: MSkill[] = [
  { id: '1', name: 'TypeScript', myRelation: EMySkillRelation.HAVE },
  { id: '2', name: 'React', myRelation: EMySkillRelation.HAVE },
  { id: '3', name: 'Node.js', myRelation: EMySkillRelation.HAVE },
  { id: '4', name: 'NestJS', myRelation: EMySkillRelation.HAVE },
  { id: '5', name: 'GraphQL', myRelation: EMySkillRelation.HAVE },
  { id: '6', name: 'Docker', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '7', name: 'JavaScript', myRelation: EMySkillRelation.HAVE },
  { id: '8', name: 'PostgreSQL', myRelation: EMySkillRelation.HAVE },
  { id: '9', name: 'MongoDB', myRelation: EMySkillRelation.HAVE },
  { id: '10', name: 'Kubernetes', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '11', name: 'Kafka', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '12', name: 'RabbitMQ', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '13', name: 'Express', myRelation: EMySkillRelation.HAVE },
  { id: '14', name: 'Fastify', myRelation: EMySkillRelation.HAVE },
  { id: '15', name: 'Vitest', myRelation: EMySkillRelation.HAVE },
  { id: '16', name: 'Playwright', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '17', name: 'Vue', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '18', name: 'Python', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '19', name: 'Git', myRelation: EMySkillRelation.HAVE },
  { id: '20', name: 'GitHub', myRelation: EMySkillRelation.HAVE },
  { id: '21', name: 'GitLab', myRelation: EMySkillRelation.HAVE },
  {
    id: '22',
    name: 'GitHub Actions',
    myRelation: EMySkillRelation.WANT_TO_LEARN,
  },
  { id: '23', name: 'GitLab CI', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '24', name: 'AWS Lambda', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '25', name: 'Angular', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '26', name: 'Zod', myRelation: EMySkillRelation.HAVE },
  {
    id: '27',
    name: 'React Native',
    myRelation: EMySkillRelation.WANT_TO_LEARN,
  },
  { id: '28', name: 'Fast API', myRelation: EMySkillRelation.WANT_TO_LEARN },
  { id: '29', name: 'Next.js', myRelation: EMySkillRelation.HAVE },
  { id: '30', name: 'Claude Code', myRelation: EMySkillRelation.HAVE },
];
